---
title: "Cleaning"
author: "Jiaxi Li"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

In this file, I first load all the data. After transforming simple returns into log returns, I remove the irrelevant variables and save all the data into a data file in the data folder.

# Load Data

```{r}
# load useful packages
library(tidyverse)
library(here)
library(dplyr)

# load the data and rename to make common names the same; only keep the REIT ones with share code 18 and exchange code above 0

Regular <- read_csv(here("data/Regular.csv"))

REIT <- readxl::read_xlsx(here("data/REIT.xlsx")) %>%
  # rename the variables as names in Regular
  rename(PERMNO = "CRSP Permanent Security Identifier",
         date = "Calendar Date",
         SHRCD = "Share Code",
         EXCHCD = "Exchange Code",
         RET = "Used Price Total Return...27",
         cap = "Market Capitalization") %>%
  # keep share code = 18 and exchange code > 0
  filter(SHRCD == 18,
         EXCHCD > 0)

Factors <- read_csv(here("data/FF5.csv")) %>%
  # rename the date and Mkt_RF
  rename(date = "X1",
         Mkt_RF = "Mkt-RF")
```


# Clean Regular Stocks

The selected "Regular" Stocks are the ones with share code 10 and 11.

```{r}
# Generate lagged capitalization for potential rebalancing and change date into yyyymm. Keep exchange code and share code. Note: RET is simple return.
Regular1 <- Regular %>%
  mutate(date = floor(date/100),
         cap = abs(PRC) * SHROUT,
         lagcap = lag(cap, n = 1)) %>%
  subset(select = -c(5,6,7,9,10))
```

# Clean REIT Stocks

The selected "REIT" Stocks are the ones with share code 18.

```{r}
# Generate lagged capitalization for potential rebalancing and change date into yyyymm. Keep exchange code and share code. Note: RET is simple return.
REIT1 <- REIT %>%
  # change date format
  mutate(date = gsub("[^[:digit:]]", "", date),
         date = floor(as.numeric(date)/100),
         lagcap = lag(cap, n = 1)) %>%
  subset(select = names(Regular1))
```


